[package]
name = "quantumsand-videogame-doggo"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
